# **SIMPLE IMPUTATION**

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np

In [ ]:
data=np.array([
    [1,2,np.nan],
    [1,np.nan,3],
    [np.nan,2,3]
])

In [ ]:
imputer=SimpleImputer(strategy='mean')
imputeddata=imputer.fit_transform(data)
print(imputeddata)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
imputer=SimpleImputer(strategy='constant',fill_value=2)
imputeddata=imputer.fit_transform(data)
print(imputeddata)

[[1. 2. 2.]
 [1. 2. 3.]
 [2. 2. 3.]]


# **KNN IMPUTATION**

In [ ]:
from sklearn.impute import KNNImputer

In [ ]:
imputer=KNNImputer(n_neighbors=2)
imputeddata=imputer.fit_transform(data)
print(imputeddata)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


# **MIN MAX SCALING**

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
data=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
scaler=MinMaxScaler()
scaleddata=scaler.fit_transform(data)
print(scaleddata)

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


# **FEATURE EXTRACTION**

# **Count VECTORIZER**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
data=['This is the first document','This document is the second document','And this is the third one']

In [ ]:
vectorizer = CountVectorizer()
bagofwords = vectorizer.fit_transform(data)
print(bagofwords.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]]


# **DICT VECTORIZER**

In [ ]:
from sklearn.feature_extraction import DictVectorizer

In [ ]:
data=[
    {'city':'New York'},
    {'city':'San Francisco'},
    {'city':'Seattle'}
]

In [ ]:
dict=DictVectorizer(sparse=False)
dictdata=dict.fit_transform(data)
featurename=dict.get_feature_names_out()
print(featurename)
print(dictdata)

['city=New York' 'city=San Francisco' 'city=Seattle']
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
